### ISSUE TITLE
Function to investigate why a target has become invalid

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#139]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

Hi @wlandau,

Wondering if there is a good way to check WHY a target is suddenly invalid? Basically which of the cues in `tar_cues` triggered the invalidation. This may be a good helper function, especially for large projects with many moving parts, or those worked on my multiple members.

**Comment by wlandau** [comment]
Yes, we should definitely support something like this. High-level information about cue status would complement the reports from `tar_visnetwork()` and `tar_outdated(targets_only = FALSE)` about which targets and functions are out of date.

What you propose is very similar to [`drake::deps_profile()`](https://docs.ropensci.org/drake/reference/deps_profile.html), which operates on a target-by-target basis. Because `targets` is so dynamic, we cannot simply look at a single target in isolation. We need to traverse the whole pipeline to even know which targets we have. What that means is we will need to check all the targets of all the cues together.

I propose a new `tar_sitrep()` function to do this. It will return a data frame where each row is a target, each column is a cue, and each element is a logical that shows whether that cue is activated. The interface will look similar to `tar_progress()` and `tar_meta()`.

Relative to `tar_outdated()`, the output of `tar_sitrep()` will be myopic. To elaborate, suppose target Z depends on target Y and target Y depends on target X. If X is invalidated, the `depend` cue for Z could still evaluate to `FALSE` in `tar_sitrep()`, even though `tar_outdated()` shows X, Y, and Z all as invalidated.

**Comment by mattwarkentin** [comment]
> It will return a data frame where each row is a target, each column is a cue, and each element is a logical that shows whether that cue is activated.

Yes! This is exactly what I envisioned in my head. I think this would be a great addition. Do you think cues which are set to `FALSE` in `tar_cues()` should be set to `NA` in `tar_sitrep()`? I say this because in my mind there is a difference between a cue that didn't happen to trigger a rebuild (i.e. `FALSE` in `tar_sitrep()`) versus a cue that couldn't possibly trigger a rebuild (i.e. FALSE in `tar_cues()`).

**Comment by wlandau** [comment]
Now that you mention it, I think we should just expose all that: a column to show if the user opted into the cue, and an independent column to show if it would have activated. We should probably also throw in the cue mode.

**Comment by mattwarkentin** [comment]
Hmm, you're probably right. I liked the idea of the rows being targets and the columns being cues. Maybe it should be a tibble of targets as rows, and two columns, one for mode and a list-column of tibbles for each cue, whether it was activated, and whether it was triggered?? Thinking out loud.
``` r
library(tidyverse)
tar_sitrep <- 
  tribble(
    ~name, ~mode, ~cue,
    "target1", "thoroguh", tribble(~cue, ~activated, ~triggered,
                                   "command", TRUE, FALSE,
                                   "depend", TRUE, FALSE,
                                   "format", TRUE, FALSE,
                                   "iteration", TRUE, FALSE,
                                   "file", TRUE, FALSE)
  )
tar_sitrep
#> # A tibble: 1 x 3
#>   name    mode     cue             
#>   <chr>   <chr>    <list>          
#> 1 target1 thoroguh <tibble [5 × 3]>
tar_sitrep %>% unnest(cue)
#> # A tibble: 5 x 5
#>   name    mode     cue       activated triggered
#>   <chr>   <chr>    <chr>     <lgl>     <lgl>    
#> 1 target1 thoroguh command   TRUE      FALSE    
#> 2 target1 thoroguh depend    TRUE      FALSE    
#> 3 target1 thoroguh format    TRUE      FALSE    
#> 4 target1 thoroguh iteration TRUE      FALSE    
#> 5 target1 thoroguh file      TRUE      FALSE
```

<sup>Created on 2020-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
On reflection, I think it would just be best to report only what the cues would say if they were enabled with `tar_cue()`. The rest is just recapitulating the user's settings, which doesn't seem worth the real estate. And if we ever do need nesting, I think I like the existing internal `tidyselect` magic more than list columns.

**Comment by wlandau** [comment]
On second (third?) thought, let's just go with what the cues actually report, which depends on the settings in `tar_cue()`. I think it's simpler to explain. To see what a cue would have done in another circumstance, you can just change the call to `tar_cue()` and watch `tar_sitrep()` respond in real time. This will be useful feedback for users to check their understanding and make sure they configured everything correctly. What we really need to know here is the final decision that `targets` makes, which means leaving nothing to mental post-processing.

**Comment by mattwarkentin** [comment]
I _think_ I am following along with what you're proposing. Sounds like you are circling back to your original thought of just show logicals for whether a particular cue was triggered for a specific target?

**Comment by wlandau** [comment]
Yes, exactly.

**Comment by wlandau** [comment]
Sketched out in https://github.com/wlandau/targets/commit/6bf393170e9bec932d67a158e996d7cd6017b089. Still needs tests.

**Comment by wlandau** [comment]
`tar_sitrep()` is now implemented.
