### ISSUE TITLE
Establishing an accurate mental model for how targets spawns and manages R processes

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#141]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

Hi @wlandau,

Just have a question about how `{targets}` spawns `R` processes to ensure that my mental model is correct. I will contrive an example for discussions sake. This question arises from monitoring the memory consumption of my multiple R processes that are running when I call `tar_make_clustermq(...)` with multiple workers.

Here's the setup. Let's say I open the terminal (I'm on a Mac, for context), and start building my pipeline by running `run.sh`, which looks like this:
```bash
#!/bin/bash

Rscript run.R
```

`Rscript` will then starts an `R` session in the terminal, and runs `run.R`, which contains:
```r
targets::tar_make_clustermq(workers = 6L)
```
It seems to me, that `{targets}` then spawns a master `R` process, and the 6 `R` worker processes. Does this all sound correct so far? In total then, there are 8 `R` processes running, the one in the shell, the master, and the workers. Right?

It is my guess that the master process dispatches the jobs to the workers as they become available, and possibly receives the target values for saving to cache. And also the master process seems to communicate back with the shell `R` process to provide the user feedback. Again, is this correct?

Will the master process and workers processes persist even if the shell `R` session is closed? Or will the master process die (and the workers too) if the `R` session that spawned it dies?

Thanks for your help!

**Comment by wlandau** [comment]
> It seems to me, that {targets} then spawns a master R process, and the 6 R worker processes. Does this all sound correct so far? In total then, there are 8 R processes running, the one in the shell, the master, and the workers. Right?

Yes, this is correct. The first layer is for reproducibility, the next layer is the master process, and then of course we have our 6 workers. If you are absolutely confident that you will always remember to restart your R session before running `tar_make_clustermq()`, then you can set `callr_function` to `NULL` to condense the outer 2 layers into a single R process, but this is not recommended because targets tend to invalidate more easily from debris in the global environment.

> It is my guess that the master process dispatches the jobs to the workers as they become available...

Exactly. The animation at <https://wlandau.github.io/targets-manual/hpc.html#clustermq> shows the intuition.

> ...and possibly receives the target values for saving to cache.

By default, each target gets shipped to a worker with its dependency targets in memory over ZeroMQ sockets. To make the worker load the data and avoid sending so much data over a socket, you can set `retrieval = "remote"` in `tar_target()`. To change the default for all the targets, use `tar_option_set(retrieval = "remote")`. The `storage` setting is similar, but it lets you choose whether the output/return value is saved to disk on a worker or the master. `retrieval` defaults `storage`.

> And also the master process seems to communicate back with the shell R process to provide the user feedback. Again, is this correct?

Yes, the master and workers ping pong back and forth to check if any data or instructions need to be sent or received. The master sends targets to workers:

https://github.com/wlandau/targets/blob/2fad956be04de00a9942f43b160937540e6d753c/R/class_clustermq.R#L103-L111

https://github.com/wlandau/targets/blob/2fad956be04de00a9942f43b160937540e6d753c/R/class_clustermq.R#L177-L187

It's a bit more complicated because there are some `send_wait()` calls for targets that are skipped or run locally (i.e. `deployment = "local"`) but that's the idea.

> Will the master process and workers processes persist even if the shell R session is closed? Or will the master process die (and the workers too) if the R session that spawned it dies?

I just double-checked this locally with `clustermq`'s multicore backend:

```r
library(targets)
tar_script({
  options(clustermq.scheduler = "multicore")
  tar_pipeline(tar_target(x, Sys.sleep(1000)))
})
tar_make_clustermq(workers = 2)
```

When I canceled the `tar_make_clustermq()` call in the RStudio IDE (the stop sign) all three external processes terminated too. But if RStudio had truly crashed (e.g. a segfault) I suspect those processes would have kept going. For actual clusters, workers do stay running in some cases, so it is important to always check the resource manager (`sequeue` in SLURM, `qstat` in SGE) to make sure those workers actually clean up. Related: https://github.com/mschubert/clustermq/issues/130, https://github.com/r-lib/callr/issues/99.

Since you mentioned memory consumption earlier, `targets` has ways to conserve more memory and pay for it with a little extra runtime. Check out the `memory` argument of `tar_target()` and `tar_option_set()` and the `garbage_collection` argument of `tar_make_clustermq()`.

**Comment by mattwarkentin** [comment]
As always, thanks a lot for such a detailed reply! Glad to see I was on the right track.
