### ISSUE TITLE
Entire pipeline is invalidated when a new function is sourced in

### ISSUE THREAD

**Issue by ndiquattro** [wlandau/targets#162]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

Thanks for working on this package, I'm very excited by the possibilities it enables! I had a question on if a behavior is expected. I have a number of files in a `functions/` directory that I source in with the `_targets.R` file like so:

```
library(targets)
library(future)
library(fs)

# Configure
options(tidyverse.quiet = TRUE)
plan(multisession)
tar_option_set(
  packages =
    c(
      "anvil",
      "arrow",
      "aws.s3",
      "fs",
      "furrr",
      "glue",
      "logger",
      "ranger",
      "tidyverse"
    )
)

# Load Globals
dir_walk(here::here("functions"), source)

tar_pipeline(
  tar_target(parsed_a, parse_a(output_table = date_name("parsed_a"))),
  tar_target(parsed_b, parse_b(input_table = "b", output_table = date_name("parsed_b")))
)
```

When I add a new file/function in the `functions/` directory my pipeline invalidates all it's targets. I'm assuming this comes from there being change in the global namespace, but it seems that would make it difficult to iteratively build up a pipeline. Is that working as intended or is there a better way to add new work to a pipeline without invalidating previously completed steps?

Thanks much!

**Comment by wlandau** [comment]
Would you post a full [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) so I can replicate this behavior on my end?

If you have different versions of the same functions in the new scripts you add, the new stuff might conflict with the old stuff, and that could cause a problem. `targets` assumes every function and every target has a unique name.

`tar_visnetwork()` and `tar_outdated(targets_only = FALSE)` can help identify the changed globals/functions which cause targets to be invalidated.

**Comment by wlandau** [comment]
Also, `targets` detects dependencies with static code analysis. That means it scans your functions for the symbols you mention and pieces together dependency relationships. Let's start with a simple pipeline with a custom function `f()`. `targets` knows `data` depends on `f()` because the command mentions the symbol `f`. Likewise, it detects that `f()` depends on `g()`.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  g <- function(x) {
    identity(x)
  }
  f <- function(x) {
    g(x)
  }
  tar_pipeline(tar_target(data, f(123)))
})

tar_make()
#> ● run target data

tar_visnetwork()
```

![](https://i.imgur.com/BT9BwHM.png)

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You can run this code analysis yourself with `tar_deps()` or `tar_deps_raw()`.

``` r
g <- function(x) {
  identity(x)
}
f <- function(x) {
  g(x)
}
library(targets)
tar_deps_raw(f)
#> [1] "{" "g"
tar_deps_raw(g)
#> [1] "{"        "identity"
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Notice above that `g()` actually depends on `identity()`. In our pipeline, `targets` ignored `identity()` because it is part of the `base` package instead of a global variable. But if we were to define a *global* symbol with the name `identity`, `targets` would consider it a dependency of `g()` and invalidate the downstream functions and targets.

``` r
library(targets)

tar_script({
  options(crayon.enabled = FALSE)
  g <- function(x) {
    identity(x)
  }
  f <- function(x) {
    g(x)
  }
  tar_pipeline(tar_target(data, f(123)))
})

tar_make()
#> ● run target data

tar_visnetwork()
```

![](https://i.imgur.com/NScpf1S.png)

``` r

tar_script({
  options(crayon.enabled = FALSE)
  g <- function(x) {
    identity(x)
  }
  f <- function(x) {
    g(x)
  }
  
  # Define a global function identity().
  identity <- base::identity
  
  tar_pipeline(tar_target(data, f(123)))
})

# identity() is now in the global environment with the other
# global dependencies, which invalidates g() and thus f() and thus `data`.
tar_visnetwork()
```

![](https://i.imgur.com/M9cEX8C.png)

``` r

tar_make()
#> ● run target data
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ndiquattro** [comment]
Thanks so much for the info! I tried to replicate the problem in a reprex way, but couldn't replicate the same behavior. However, I changed my code from using `tar_pipeline()` directly, like:

```
tar_pipeline(
  tar_target(),
  tar_target()
)
```

to feeding `tar_pipeline()` a list:

```
targets <- list(tar_target(), tar_target())
tar_pipeline(targets)
```
after noticing that's how `tar_script()` does it and the problem isn't happening anymore.! I suppose I either had messed up my previous pipeline definition or my cache somehow? Thanks for your help, looking forward to using targets more!

**Comment by wlandau** [comment]
Glad the problem went away. If it does come back, please post a reprex if you can and I will dig into it and try to figure out what is invalidating the targets.

I highly doubt the switch to a target list instead of `tar_pipeline()` made the difference. What often happens is people change some code or move files around and then forget about the change (another reason why Make-like tools ensure reproducibility).
