### ISSUE TITLE
Consider a "batches" argument to `cross`, and `map`?

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#171]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md) and the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Please format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

The manual recommends batching here: https://wlandau.github.io/targets-manual/dynamic.html#batching

As I understand it, having longer-running targets helps the master process deal with its job due to lower overhead but having longer running targets may mean that targets use up too much memory.

One way to achieve both goals might be for drake to, rather than send the work for one target at a time, send batches of targets.

When combined with:
```
tar_option_set(storage = "remote", retrieval = "remote", memory = "transient")
```
this can keep the running time of the batch long, while keeping the memory usage of the target low.

The manual suggests that we should be able to use loops within the code of each target to control the running time of the target. However, this only allows us to manipulate the running time of the target at a single stage of the analysis when the analysis depends on multiple stages of analysis on the same groups. Furthermore, it limits our ability to control memory usage, especially if the memory usage is primarily due to the loading of input targets.  

The use case I am currently facing has two large stages that operate on the same groups in sequence: first a `cross` followed by a `map` over the result of the first target. Both targets use the same amount of memory but the first uses much more CPU time that the second. Given that the maximum running time of a target in the second stage is determined by the settings from the first stage, I have no way of independently manipulating the running time and memory usage of the two stages. Furthermore, the memory usage of the first stage is higher than I would like to be.

**Comment by wlandau** [comment]
I am sympathetic to this proposal. In fact, it was one of the first things I considered when I started thinking seriously about batching. However, the more I thought about it and pieced together what it would take (systemic modifications to the priority queue and scheduling algorithms) I realized that it would open a Pandora's Box of new issues and technical debt without necessarily solving the motivating problems.

Overhead comes from having a large number of targets. Even if `storage` and `retrieval` are both `"remote"` and there is very little data to send to and from workers, the master process still needs to coordinate a lot of steps and conduct a lot of reasoning on each one, and it may not have time to farm out to all of 200+ workers. (Some targets may finish before the pipeline can reach max occupancy.) A built-in batching solution would add even more reasoning and thus more overhead, which may or may not be overshadowed by longer-running jobs.

User-level batching as described at https://wlandau.github.io/targets-manual/dynamic.html#batching will always be superior because it addresses the root cause of overhead. And because of the freedom users have with custom code, workarounds are usually possible.

It may become necessary to just reduce the size of the in-memory objects you manage. The user almost always has control over that. For example, when I construct Bayesian statistics pipelines in `targets`, I never save all the posterior samples. I only return the numerical summaries I know I will need: posterior quantiles and convergence diagnostics. In batch form, each batch/branch is a set of model runs represented by rows of a tidy data frame. An example is at https://github.com/wlandau/targets-stan. Similarly, in deep learning workflows, I recommend discarding most of the fitted model objects and just hold on to a tidy data frame summary of the results: https://github.com/wlandau/targets-keras.

Whether it's Bayesian statistics or deep learning, each iteration within the batch need only take up the memory required for one model run. You can summarize each model fit and run `gc()` before each successive iteration and batch size matters less.

My academic training includes a lot of Bayesian statistics, so always have it in mind and can develop features and workarounds fit for purpose. Likewise for machine learning, sort of. (I rarely use machine learning for my daily work, but I feel like I have made an effort to pick up enough to be useful in the workflow side of things.) But from #169, it looks like you are doing a lot of spatial data analysis on shapefiles. That's an area in which I do not have direct experience, so I do not understand the relevant goals or computational constraints. An example motivating project would make me much more useful. 

If you really do need to create a large number of large data objects, in the most extreme case, you can avoid many of the memory problems by working with dynamic files, e.g. `tar_target(format = "file")`. A dynamic file branch target can be an arbitrary collection of files and directories which downstream targets treat as an irreducible unit of data. Each downstream batch should iterate over the individual paths of the upstream file batch.
