### ISSUE TITLE
Dealing with a list of targets as input for another target

### ISSUE THREAD

**Issue by MxNl** [wlandau/targets#189]
## Description

In my targets pipeline I have functions that use many (>10) targets as input. An example for such a function could be a function that joins the tibbles behind the targets. To not always have to list them as input and reduce repetition I made a list containing the targets names as shown in the example. However, I am probably over-thinking this and not seeing a simple and much more elegant solution for that. Any hint is welcome.

## Reproducible example

My `_targets.R` file looks like this

```{r}
library(targets)


target_names <- 
  list(
    "target_a",
    "target_b"
  )

paste_vectors <- 
  function(targets_list){
    targets_list %>% 
      map(tar_read) %>% 
      reduce(c)
  }


options(tidyverse.quiet = TRUE)
tar_option_set(packages = c("tidyverse"))

tar_pipeline(
  tar_target(
    "target_a",
    1:5
  ),
  
  tar_target(
    "target_b",
    4:7
  ),
  
  tar_target(
    "reduced_data",
    paste_vectors(target_names)
  )
)

```

if I run `tar_make()` I get the following error message:
```
x error target reduced_data
Error : target .x[[i]] not found .
```

with regard to this issue, I don't understand the difference in the behaviour of
```{r}
tar_read("target_a")
```
vs
```{r}
"target_a" %>%
  tar_read()
```

**Comment by mattwarkentin** [comment]
Hi @MxNl,

As far as I understand, `tar_target()` needs to see bare symbols (i.e. `target_a`, not `"target_a"`) to be able to detect dependencies among targets. So your technique was close but fails, in part, because passing character strings won't work. I also think you can eliminate the `paste_vectors()` function altogether. `targets` will load the targets as necessary, so you shouldn't need to load them manually in this way.

Here is an example that I think doest what you want it to do. First, we convert the character strings to bare symbols with `purrr::map()` and `rlang::sym()`. Then we use the splice-unquoting ("big-bang") operator to take the list of symbols and turn it into a comma-separated list of arguments. In essence, `tar_target(foo, c(!!!list(a, b)))` will become `tar_target(foo, c(a, b))`; a bit of misdirection, but it works.

``` r
library(targets)

tar_script({
  target_names <- 
    purrr::map(list(
      "target_a",
      "target_b"
    ), rlang::sym)
  
  options(tidyverse.quiet = TRUE, crayon.enabled = FALSE)
  tar_option_set(packages = c("tidyverse"))
  
  tar_pipeline(
    tar_target(
      "target_a",
      1:5
    ),
    tar_target(
      "target_b",
      4:7
    ),
    tar_target(
      "reduced_data",
      c(!!!target_names)
    )
  )
})

tar_make()
#> ● run target target_a
#> ● run target target_b
#> ● run target reduced_data
tar_read(reduced_data)
#> [1] 1 2 3 4 5 4 5 6 7
```

---

> with regard to this issue, I don't understand the difference in the behaviour of...

The reason the first one works is because `tar_read()` is able to accept character strings and quotes them internally as symbols. If you look inside the `tar_read()` function, you will see this code:
```r
name <- deparse_language(substitute(name))
```
This bit of code will capture characters as symbols. But if you pipe into a function, the LHS gets evaluated before `tar_read` can gets the argument and quotes it. Regarding our above example:
``` r
# Neither of these will work
"reduced_data" %>%
  tar_read()
#> Error: target . not found

reduced_data %>%
  tar_read()
#> Error in eval(lhs, parent, parent): object 'reduced_data' not found

# These will work
tar_read("reduced_data")
#> [1] 1 2 3 4 5 4 5 6 7
tar_read(reduced_data)
#> [1] 1 2 3 4 5 4 5 6 7
```

**Comment by wlandau** [comment]
I completely agree with @mattwarkentin. This is why I always recommend visualizing the graph to make sure functions and targets are properly connected.

``` r
library(targets)
tar_script({
  target_names <- list("target_a", "target_b")
  paste_vectors <- function(targets_list){
    targets_list %>% 
      map(tar_read) %>% 
      reduce(c)
  }
  options(tidyverse.quiet = TRUE)
  tar_option_set(packages = "tidyverse")
  tar_pipeline(
    tar_target(target_a, 1:5),
    tar_target(target_b, 4:7),
    tar_target(reduced_data, paste_vectors(target_names))
  )
})

tar_visnetwork(targets_only = TRUE)
#> <pipeline with 3 targets>
```

![](https://i.imgur.com/cjRIbI8.png)

``` r

library(targets)
tar_script({
  target_names <- rlang::syms(c("target_a", "target_b"))
  options(tidyverse.quiet = TRUE, crayon.enabled = FALSE)
  tar_option_set(packages = "tidyverse")
  tar_pipeline(
    tar_target(target_a, 1:5),
    tar_target(target_b, 4:7),
    tar_target(reduced_data, c(!!!target_names))
  )
})

tar_visnetwork(targets_only = TRUE)
#> <pipeline with 3 targets>
```

![](https://i.imgur.com/pDIi5Mf.png)

<sup>Created on 2020-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Behind the scenes, `targets` uses static code analysis to detect the literal symbols you mention in each target's command and resolve dependencies that way. Behind the scenes, it uses `codetools::findGlobals()` with some modifications. The `tar_deps()` function allows you to replicate the symbol detection on your end. Details: https://wlandau.github.io/targets-manual/practice.html#dependencies.

By the way, `tar_combine()` from the [`tarchetypes`](https://github.com/wlandau/tarchetypes) is another way to aggregate targets.

``` r
library(targets)
tar_script({
  library(tarchetypes)
  target_names <- rlang::syms(c("target_a", "target_b"))
  options(tidyverse.quiet = TRUE, crayon.enabled = FALSE)
  tar_option_set(packages = "tidyverse")
  a <- tar_target(target_a, 1:5)
  b <- tar_target(target_b, 4:7)
  c <- tar_combine(
    name_combined,
    a,
    b,
    command = bind_rows(!!!.x)
  )
  tar_pipeline(a, b, c)
})
tar_visnetwork(targets_only = TRUE)
```

![](https://i.imgur.com/aqIpLp3.png)

<sup>Created on 2020-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MxNl** [comment]
@mattwarkentin, @wlandau thanks a lot for your help and hints!!!
