### ISSUE TITLE
Question -- How to set last priority for some targets?

### ISSUE THREAD

**Issue by mik3y64** [wlandau/targets#190]
First question: Hi, for some large targets pipelines, some targets were run in wrong order, even though the target is the last in the pipeline. targets don't seem to respect the order of target specified in `targets::tar_pipeline`. So I want to be able to set some targets to be run as the last priority. However, the `priority` argument in `tar_target` has to be specified between 0 and 1. Targets with priorities closer to 1 get built earlier. How do I set it to be the "last" priority? Setting `priority = 0` does not work. It is necessary user is able to set some targets to be run as the last priority. 

```r
library(targets)
targets::tar_pipeline(
  tar_target(data, airquality),
  tar_target(data2, mtcars, priority = 0)  # This does not work. I want result to be run as the last target. 
)
```

Second question: I understand that most targets are run in order based on the dependency but for some complicated pipelines or rare cases, it makes sense for targets to respect the order of individual target specified in `tar_pipeline`. What is the reason that targets don't respect this order? It is confusing and hard to debug for very large pipelines that the order of targets don't respect the order specified by the user in `tar_pipeline`. Can we make it a new feature request?

**Comment by wlandau** [comment]
That's by design. `targets` ignores the order in `tar_pipeline()` and respects the topological order of targets in the graph. There are many different possible topological orders, and `tar_make()` uses the one from `igraph::topo_sort()`. Unfortunately, there is now way to tell `topo_sort()` about the priorities you set in `tar_target()`. Priorities are intended for parallel computing scenarios, and they actually only apply to `tar_make_future()` and `tar_make_clustermq()` (I need to note that in the docs). `tar_make_future()` should work without any change on your end. (By default, it uses `future::plan(future::sequential)`, which is the same as running locally.)
