### ISSUE TITLE
A multitude of thoughts for evolution from drake to targets

### ISSUE THREAD

**Issue by billdenney** [wlandau/targets#193]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Apologies that this will be both a bit meandering (in that it will cover a few different items) and that I have not been able to review targets itself in detail.  And, some of this may also be already handled within the package.  (An offline email to Will gives the rationale for this not being as focused as a good issue should be.)

1. I saw in https://wlandau.github.io/targets/articles/need.html#lighter-friendlier-data-management that targets have a directory named `_targets/objects/target_name`.  One of the issues that I have in `drake` moderately often is related to windows path length requirements.  I like that the directory structure will be simpler for the user (though I've not dived into the `.drake` directory in the past), but I worry that I may have a long target name that will then break in Windows for the path name being too long.  Before `targets` goes too far down this path, it would be helpful to have some way to ensure that path names in the data cache are handled in a way that is inclusive of working in Windows.
2. Similar to number 1, a challenge in `drake` was the use of long filenames and hashing them in windows via `file_in()`.  It would help to ensure that similar functionality watched for long filenames in Windows from the start, too.
3. `rstan` and other packages (often using Rcpp, in my experience) interact with the global environment in ways that cause issues with `drake` due to loss of reproducibility by reaching outside of the local environment.  It would be helpful if somehow, a faux global environment could be created either for every target (my preference) or when requested by the user manually.
4. Sometimes, I want to create temporary files such as downloaded files or compiled files during a `drake` run (e.g. download something large, compile using the `mrgsolve` library).  It would be helpful if there were a defined location within the `_targets` directory where these could be created.  My initial thought it that it could be named similar to `_targets/userdata/`, and there could be a function like `tar_tempfile()` and `tar_tempdir()` that would give a location within that folder structure or the user could manually create something in there.  (If this is of interest, I'm sure that it will take a good bit more thought for the best way to implement.)
5. I often want to have a pipeline rerun when new versions of packages are installed.  One of the intentional limitations of `drake` was that imported package functions were considered unchanged.  It would be helpful to have some form of option to link the package version with the function so that it would rerun if the package were updated.  (For example, when finding `tar_make`, it could be found as `targets(0.0.0.9002 [maybe including git hash, too])::tar_make`.  There is definitely a better way to store it than that, but it communicates the intent.)
6. Related to 5, it would also be useful to have a deep search that would also search the dependencies in some way.  The simplest may be to look at all dependencies of a package and store their versions as part of the function as well.  (For example, when finding `tar_make`, it could be found as `targets(0.0.0.9002)[callr(version) cli(version) codetools(version) etc.]::tar_make`.  Again, there is definitely a better way to store it than that, but it communicates the intent.)

**Comment by wlandau** [comment]
Hi Bill, thanks for the feedback.

1. First of all, `targets` does create Base32-encoded key files in the data store, so you never have to deal with https://github.com/richfitz/storr/issues/94 ever again. If you still have problems with long file paths, it may be time to reconsider where you store your pipelines or shorten your target names. [`tarchetypes::tar_map()](https://wlandau.github.io/tarchetypes/reference/tar_map.html) makes it easier to define custom target names than in `drake`'s static branching, and automatically generated target names do not get out of hand as easily. Let me know if you want help with this.
2. If I understand you correctly, I think `targets` solves this issue by design. For each `file_in()`, `drake` Base32-encodes the file path and uses the value in a new key file. In `targets`, all the file paths are stored in a `data.table` file in `_targets/meta/meta`. As long as you do not use characters `|` or `*` in the file name, you should be all set (and `targets` does warn you about illegal characters in file paths).
3. `targets` always creates a fresh `callr` process to run the pipeline unless you manually set `callr_function = NULL` in `tar_make()`, so the risk of self-invalidating workflows is smaller. Creating a faux global environment comes with its own risks. I tried to do that in the early days of `drake`, and it turns out to be super tricky to assign functions to a different environment in a way that respects the relationships among closures. I also considered `source()`'ing `_targets.R` into its own environment, but that usually breaks down because users have their own `source()` calls in that script, which automatically use `globalenv()`. I have wanted to find some other workaround to this for years, but I am convinced there's really nothing I can do without breaking the user's functions. In the case of `rstan` specifically, I recommend switching to `cmdstanr` for the sake of better infrastructure in general.
4. I do not think this is very common, and I intend `targets` and its data store to stay rigid and well-defined in scope. If you really need temp files to be local to the project root, you could implement a custom set of utility functions that maintains a temporary data store outside `_targets/`.
5. After revisiting the issue of packages several times over the course of `drake`'s development, I have deliberately chosen to not invalidate targets based on the versions of packages or package functions. In most cases, I think this would lead to brittleness: unnecessarily invalidations and redundant computation. Instead, I fully endorse `renv` for this because it enhances reproducibility while `reducing` brittleness. @mattwarkentin even implemented a `tar_renv()` function to make this easier. If you want to invalidate some of your targets based on the version of the package, there are workarounds using `targets::tar_cue()` and `tarchetypes::tar_change()`.
6. Again, I think this direction would create brittleness without adding much value in most use cases, and I think scraping packages is a deep enough topic to go in its own package.

**Comment by billdenney** [comment]
Thanks for the thoughts!

My only added note is that I don't always have options for file names (to shorten their length, for reasons that are a bit complicated for my processes).  I do have some options for folder locations, but not always that, either (again for ways in my processes that would be a bit specific to me, I understand).

Overall, I wonder if it may be possible to put a hook in for a module to shorten the names of directories and files within the `_targets/` directory.  I don't know if the windows name shortener would be part of canonical `targets`, but I assume that long file names or long target names will cause issues for Windows users over time, and preventing those problems seems like something that may be easier to bake in earlier rather than later.

**Comment by wlandau** [comment]
All external files are tracked with `tar_target(..., format = "file")` or `tar_target(..., format = "aws_file")`. In both cases, the paths are stored inside the `_targets/meta/meta` data table, and no extra key or data files are created. So we completely avoid the problem `drake` had with super long Base-32 encoded key files that showed up in https://github.com/richfitz/storr/issues/94, https://github.com/ropensci/drake/issues/628, and https://github.com/ropensci/drake/issues/1263.

For most other targets, the path is of the form `PROJECT_ROOT/_targets/objects/TARGET_NAME`. Almost all the path length comes from `PROJECT_ROOT`  and `TARGET_NAME`. It is the user's responsibility to shorten `PROJECT_ROOT`  and `TARGET_NAME`, and almost all users have the power to do so. I am not willing to shorten `_targets/objects/` because it would disrupt the interpretable naming conventions I established throughout the package, and it would not conserve many characters anyway.

`targets` succeeds by doing 20% of the work to support 80% of the functionality. It needs to avoid rabbit holes and technical debt, especially for rare edge cases like this one. The structure and names of the data store files will not change.
