### ISSUE TITLE
Is this ready to migrate from drake, how difficult is this migration, & what are the gotchas?

### ISSUE THREAD

**Issue by matthewstrasiotto** [wlandau/targets#196]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] **[NA]** ~For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot.~

## Question

Hi there! I use drake on a HPC system & I am both excited & nervous about the potential of migrating to targets. 

I also have a couple of concerns

### Concerns

From the docs, `targets` is far more opinionated than `drake` in terms of how it stores its data & where. Personally, I'm in agreeance that simplifying the cache mechanism to something more transparent is a good thing, as debugging & accessing the drake cache was easy for me, the pipeline guy, but it was often a source of friction for people new to it. 

That being said- I notice that `targets` says the following: 

> In addition, the _targets/ data store always lives in the project root.

This is where I get nervous. 

In my project/HPC env we actually have a few different data extracts, a 15GB limit on our /home mounts, & we store all of our data on a mounted share for the project. 

I have a few small bespoke packages for managing & swapping between our different extracts, & their respective drake caches. 

If targets always forces me to use `file.path(here(), "_targets")` (roughly), swapping my extract will be a bit tricky.

The solution that jumps to mind is replacing `_targets` with a symlink to the respective directory on the data share, and it's not a solution I particular relish, as presently different sessions / runs are able to target different datasets simeltaneously, & this would not be true for this symlink cludge. 

I understand that this degree of opinionation is by design, to reduce astonishment & encourage best practises, but I wonder if you consider it worth accomodating my use-case?

**Comment by wlandau** [comment]
I understand that the paternalistic behavior may affect project management techniques that previously worked with `drake`. However, as with #193, this is one of those uncommon edge cases that I am not willing to solve with extra flexibility in `targets` itself.

Other workarounds seem possible: for example, switching to the data share directory at the last minute.

```r
# _targets.R
source("R/functions.R") # Needs to be at the project root (in /home/YOU, presumably).
setwd("DATA_SHARE")
tar_pipeline(...)
```

This should work as long as any external file paths to data and R Markdown reports are adjusted accordingly. Once the pipeline starts actually running, `targets` will [resist subsequent changes to the working directory](https://github.com/wlandau/targets/blob/d21647aadc416b9f1aacf5d3636c3042fa89edfe/R/class_build.R#L20).

Even better: unlike `drake`, `targets` supports seamless cloud storage integration with Amazon S3: https://wlandau.github.io/targets-manual/cloud.html. If your organization allows this, it will be much more convenient. And you get data versioning for free since you can set up an S3 bucket to track the versions of files.

**Comment by matthewstrasiotto** [comment]
Not the answer i hoped for, but that's a pretty sweet point about AWS, they've tried to sell to us before and we actually might have ethics for it 
Thanks anyway @wlandau
