### ISSUE TITLE
Does changing the code in a sourced r file causes targets to rerun the related analysis?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#234]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Does changing the code in a sourced r file causes targets to rerun the related analysis? I thought that would be the expected behaviour but it is not happening unless I change the code in the tar_target() i.e. adding something like `%>% mutate(tmp = "")  %>% select(-tmp)` after the function I called in the script.

## Reproducible example
Checking what is the expected behaviour first. I am not too certain how to add a reprex for this because it seems to be a moving target but I can try...

**Comment by liutiming** [comment]
update: it appears when the target rule name is the same as the function name that the target rule runs.

**Comment by wlandau** [comment]
As I think you realized, if you source R scripts from within `_targets.R`, then `targets` tracks the functions and global objects in memory rather than the source files themselves. The best way to see what those objects are is to visualize the dependency graph with `tar_visnetwork()`. [Here is an example](https://wlandau.github.io/targets-manual/walkthrough.html#changes) describing how to make sure your functions are connected properly and what happens when a function changes. Functions nested within top-level functions are tracked as well. If you make a nontrivial change to a function, this will invalidate downstream targets. (Trivial changes like whitespace and comments are ignored.)

Related: to track changes to a physical file such as an external input dataset, create a dynamic file target: a `tar_target()` with `format = "file"` and a command that will return the path to the file ([example here](https://github.com/wlandau/targets-keras/blob/0735d8e290bd93269171cc9660c396960a8cd932/_targets.R#L25-L30)).

**Comment by wlandau** [comment]
Also, as you noticed, all names must be unique (target names, global object names, function names). Always check the graph to make sure your pipeline is constructed correctly before committing to a long computation with `tar_make()`.

**Comment by liutiming** [comment]
Yup thanks so much! I am thoroughly enjoying the workflow now. 

What would be a good strategy for naming? Sometimes the function that target rules call are intended to do the same thing as the target so I just add `_f` after the function name to avoid confusion. 

Perhaps it is good to write more generalized functions to avoid this issue? Would love to hear your opinions here.

**Comment by wlandau** [comment]
> What would be a good strategy for naming? Sometimes the function that target rules call are intended to do the same thing as the target so I just add _f after the function name to avoid confusion.

Those suffixes work, and they have the advantage of grouping functions with similar targets when you sort names alphabetically. Alternatively, the naming convention could treat functions as actions and targets as objects. So you could write functions as `verb_noun()` and targets as just `noun`.

> Perhaps it is good to write more generalized functions to avoid this issue? Would love to hear your opinions here.

That's usually a good strategy. The only downside for `targets` is that if you make a nontrivial change to a single function, the change invalidates everything downstream. So if you write more functions that effectively partition targets into smaller dependency groups, fewer targets will get invalidated in response to a change to a single function, and  `tar_make()` will bring all your targets up to date more quickly.
