### ISSUE TITLE
How to include automated tests in the pipelines 

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#236]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

Again thank you very much for this awesome package and really prompt replies! I am wondering how would you include automated tests to to ensure the result passes a few sanity checks before running the next step, or to ensure refactorization was done correctly?

**Comment by wlandau** [comment]
I have found it best to treat pipelines and tests totally separately. I think tests should apply to the supporting functions you write for the workflow, and they should be scaled down to run quickly. Because pipelines are usually computationally expensive, they are better suited to validation than testing: for example, running a large number of models in a simulation study to check and the results match expectations.

In general, I recommend developing the pipeline slowly and gradually with lots of checks along the way:

1. Add a target.
1. Check the pipeline with `tar_visnetwork()`.
1. Run the pipeline (`tar_make()` etc.).
1. Load the target with `tar_load()` or `tar_read()` and do exploratory data analysis.
1. Repeat.

An example of this strategy is at https://wlandau.github.io/rpharma2020.
