### ISSUE TITLE
Is there a function for "dry run"

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#240]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question
"dry run" means to show users how the branching will be done without actually running the command. So far the closest function I have found is `tar_pattern()` but that will require users to load some data/workspace first. It will be easier to use if there is something like an option in `tar_make()` to tell it that it does not need to run the functions or if visualization can show the branching.

**Comment by wlandau** [comment]
`tar_pattern()` went through a bunch of initial versions, and the current one requires no data or workspace to load.

```r
> tar_pattern(
+     cross(x, map(y, z)),
+     x = 2,
+     y = 3,
+     z = 3
+ )
# A tibble: 6 x 3
  x     y     z    
  <chr> <chr> <chr>
1 x_1   y_1   z_1  
2 x_1   y_2   z_2  
3 x_1   y_3   z_3  
4 x_2   y_1   z_1  
5 x_2   y_2   z_2  
6 x_2   y_3   z_3 
```

I do not think we can handle dry runs in general in `tar_make()`. By design, dynamic branching means defining new targets based on the values of previous targets. To do that, we need to run some kind of command and get output. Some upstream targets would need to run first, and then we would need to mock the commands of the downstream patterns. Seems like a lot of work, and I am not optimistic about the end product.

**Comment by liutiming** [comment]
OK thanks! I understand that `tar_pattern() `does not require loading dataset, but running it on a simulated dataset does take a bit of effort to create the simulated dataset in the first place but I understand it must take a lot of effort to calculate the downstream branching without getting the value in the first place...

**Comment by wlandau** [comment]
A scaled-down run is kind of like a dry run. For testing and experimentation purposes, you can write something like `tar_target(pattern = head(map(x)))`. Then when you are ready to scale up, you can run the rest of the branches with `tar_target(pattern = map(x))` and your previous branches should still be up to date.
