### ISSUE TITLE
Targets seem to be able to cope with 1000 branches?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#246]
I need to run 1000 permutation tests to get empirical p values and I have to assign each job to a worker because of the computation involved. To my pleasant surprise, targets seem to be able to run through the list of branches and submit each at about 1-2 sec/branch. Of course because of the fair use policy the current number of jobs running is about 200+ and the rest are pending but all seem to be working well? When should I expect to see the performance bottleneck due to the number of branches? Is it after I start building dependencies on this step?

**Comment by wlandau** [comment]
Glad to hear `targets` still fast enough for 1000 targets. If you are not running into any performance issues, by all means please keep doing what you are already doing.

If you plan to add thousands more targets though, at a certain point you may notice a gradual slowdown. It may take `tar_make()` a minute to skip up-to-date targets, and likewise with `tar_outdated()` and `tar_visnetwork(outdated = TRUE)`. It's hard to say exactly when this slowdown will occur because everyone's hardware is different, but you can pretty easily create a use case that seems simple but still taxes performance. Below, each target is doing basically nothing, but there are 100001 of them, and my Macbook takes a long time to get through them all.

```{r}
# _targets.R
library(targets)
tar_pipeline(
  tar_target(x, seq_len(1e5)),
  tar_target(y, x, pattern = map(x))
)
```

This overhead is unavoidable because there is so much to do for every single target. I have done a lot of [profiling](https://r-prof.github.io/proffer/) and [benchmarking](https://github.com/joshuaulrich/microbenchmark/) on the scenarios I am familiar with, and I am not sure how to make this faster. So for users who come to me with this problem, I usually recommend batching as [described here](https://wlandau.github.io/targets-manual/dynamic.html#batching) or with [`tarchetypes::tar_rep()`]() if possible. (Clearly you already saw this.) But again, since this is not a problem for you, I see no reason for you to refactor your pipeline.

**Comment by wlandau** [comment]
> about 1-2 sec/branch

Given what you told me, I see this as the only potential reason to consider batching. 1-2 seconds seems quite light for a single target. Clearly some targets are going to be quick, but ideally not most of them in a heavy-duty workflow. Just saying for future reference, not necessarily for this particular workflow.

**Comment by wlandau** [comment]
> Of course because of the fair use policy the current number of jobs running is about 200+ and the rest are pending

I am glad you brought this up, and I hope onlookers have similar practices. For large collections of targets, the number of workers will often be less than the number of jobs. I routinely submit hundreds of targets to my company's cluster, but I follow the guidelines of my sys admin and only submit 50-100 workers at any given time.

**Comment by liutiming** [comment]
Oh I love the idea of `tar_rep`! This may actually be a more appropriate tool for running a permutation test. I was not aware of this because it was not included in the user manual. However, I do not see the mentioning of seed in the [function reference](https://wlandau.github.io/tarchetypes/reference/tar_rep.html). Does it keep the seed and hence ensuring reproducibility?

If the bottleneck that we are talking about is running through a list of targets, then I suppose I may already been experiencing some of it: previously I created a target that created 1000+ figures, hence 1000+ branches. I was just trying my luck before attempting to refactor the code and yes the time it takes to run through the list is probably higher than than the time to create each figure and the number of workers I assigned did not help - it took almost the same time as running on a single thread. 

I guess another bottleneck is probably the time it takes to compute the targets - sometimes I see targets get stuck at one target without running anything. For those cases I either re-run the targets (sometimes helped) or run them locally because the overhead is not worth it. 

I am thinking whether it is possible to have a semi-"ignore" option. Users can choose to ignore certain targets (in my case it could be the figure generation) and these options will be assumed updated and taken out of the computation when targets are run. Users can either choose to validate them by force (before presenting them) and targets can enforce reproducibility by forcing the ignored targets to be run on a weekly/monthly basis. This may be a good compromise among reproducibility, effort to refactor code just for targets, and speed of running. 

This may be helpful because certain times running a lot of workers are just inevitable due to duration limit on the cluster, and even batching with future will slow down the process when previously someone could just submit all jobs to the cluster without experiencing the targets overhead.

**Comment by wlandau** [comment]
> Oh I love the idea of tar_rep! This may actually be a more appropriate tool for running a permutation test. I was not aware of this because it was not included in the user manual.

Probably belongs in the section on batching, now that you mention it.

> However, I do not see the mentioning of seed in the function reference. Does it keep the seed and hence ensuring reproducibility?

`targets` sets a unique fixed reproducible random seed for each target. Different targets (including different dynamic branches) run with different seeds, and the target will keep its seed for subsequent runs as long as you do not change its name. You can recover the seed with `tar_meta()`. For [`tarchetypes::tar_rep()`](https://wlandau.github.io/tarchetypes/reference/tar_rep.html), each batch is a target, and then reps happen sequentially. `targets` does not assign rep-specific seeds, but because of the sequential order, the results should still be reproducible. 

> If the bottleneck that we are talking about is running through a list of targets, then I suppose I may already been experiencing some of it: previously I created a target that created 1000+ figures, hence 1000+ branches. I was just trying my luck before attempting to refactor the code and yes the time it takes to run through the list is probably higher than than the time to create each figure and the number of workers I assigned did not help - it took almost the same time as running on a single thread.

Yup, it's just a lot of work for the main process. 

> I guess another bottleneck is probably the time it takes to compute the targets - sometimes I see targets get stuck at one target without running anything. For those cases I either re-run the targets (sometimes helped) or run them locally because the overhead is not worth it.

> I think targets already have top-notch reproducibility practice than many tools (e.g. snakemake does not re-run even after custom scripts are modified) so it may be good to give an option to the users for speed and ease of use sometimes.

Ignoring upstream code like functions and global objects is harder. One way is to put these objects in a package and then do not supply the package to the `imports` argument of `tar_option_set()`. Another way to ignore a custom function is to supply a custom environment to `tar_option_set(envir = ...)` that only includes the functions and global objects you want to be able to invalidate targets. (The environment should inherit from `globalenv()` so packages still work.)

It's hard to say exactly why. Sometimes if a target has a lot of dependency data it may take a while to send it to a worker on a cluster. If your cluster has NFS then `tar_target(retrieval = "worker")` might help in some use cases. Running locally decreases the overhead of sending to a cluster, but it ties up the main process for as long as it takes to run the targets. And sometimes `clustermq` workers fail silently for various reasons and the only way to see the errors is to opt into creating worker logs in advance.

> I am thinking whether it is possible to have a semi-"ignore" option. Users can choose to ignore certain targets (in my case it could be the figure generation) and these options will be assumed updated and taken out of the computation when targets are run. 

You can ignore downstream targets: just set the `names` argument to `tar_make()` etc. to the upstream targets you want. If I run `tar_make(names = starts_with("models_")`, for example, `targets` will run the upstream data if needed and then all the model targets, but it will skip everything after the targets whose names start with `"models_"`. For upstream targets you already built, you can set `tar_cue(mode = "never")` to forcibly skip them, but `tar_make()` will still formally check and acknowledge them, which may take some time if you have many targets. There is no other way to completely shortcut this because `tar_make()` is dynamic and it needs to use upstream targets for dynamic branching.

**Comment by mschubert** [comment]
> And sometimes clustermq workers fail silently

This should not happen much longer :grimacing:
