### ISSUE TITLE
Multiple pipelines in a single project

### ISSUE THREAD

**Issue by arnold-c** [wlandau/targets#252]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] ~~For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:~~
 

## Question

I'm very fresh to the idea of using pipelines in analysis, so sorry if this questions is obvious, but I tried looking in the `{targets}` and `{drake}` user manuals and couldn't find an answer. I also believe that it is a distinct question from #163, but please close/move this question if you think it is a repeat.

In the `{targets}` package, what is the best way to create and use multiple pipelines that achieve different analyses within a single project? 

For example, let's say I have data that requires extensive EDA and I plan to knit a report using `tarchetypes::tar_render()`, but do extensive model fitting and evaluation and want to keep the reports and analysis in separate pipelines due to length. My understanding is that a single `_targets.R` file is needed in the project, and I would therefore just define separate pipelines for each report, within the same `_targets.R` file. If the analysis pipeline required some feature engineering that resulted from the EDA I would just write a dataframe in the EDA pipeline that is then imported in the analysis pipeline (and therefore only loaded as a new object if there have been any changes).

Is this the ideal workflow, or is there something else I should be doing, like specifying different `_targets.R` files for each pipeline?

**Comment by wlandau** [comment]
It ultimately depends on your personal preferences, but I think separate pipelines in the same project would tend to get cumbersome. If the pipelines operate completely independently from one another (if you plot the graph and there are disconnected groups of vertices) then I think it would be easier to maintain them as separate projects unless that would involve a lot of duplication. Otherwise, if all your targets are connected, then I recommend maintaining a single pipeline. It is a stylistic choice whether to define those targets in separate pipeline objects of lists of target objects in the same `_targets.R` file. You could even define those sub-pipelines in separate scripts, `source()` them in `_targets.R`, and then just combine all the objects together. This is similar to how [example projects](https://github.com/wlandau/targets-stan) split up the code into multiple functions in files in the `R/` folder. Other than that, the size of a single overarching pipeline does not start to incur performance penalties until you get to the thousands of targets.

Related: coincidentally, I am actually about to deprecate pipeline objects entirely on the user's end. By the time `targets` is on CRAN, you will be able to end `_targets.R` with a list of `tar_target()` objects instead of a `tar_pipeline()` object. I think this will demystify usage for new folks.

Related:
