### ISSUE TITLE
Mege two targets directories?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#255]
Hi @wlandau , what would you expect to happen if I merge two targets directories by combining the _target scripts and _target directory? Assuming there are no duplicate names. This may be useful because sometimes it is easier to construct different models first and then combine the workflows to compare.

**Comment by wlandau** [comment]
I don't usually recommend this because it breaks the abstraction and it leaves a lot of room for error, but if there are no duplicate names, you should be able to aggregate all the data in `_targets/objects/` and row-bind the data lines in `_targets/meta/meta`. If there are duplicate names, you can override the old objects with the new ones and put the new metadata below the old metadata. 

`targets` deliberately pushes users to avoid creating multiple sub-projects under the same roof. Things tend to get messy when people do that, and there are cleaner and more reproducible workarounds for optimally managing a workflow. 

Related: what we really need is a Git-like data versioning system coupled with a GitHub-like service that can handle the large files generated in big data workflows. Relative to `drake`, `targets` tries to anticipate this by cleaning up its own data storage system so small projects can push all of `_targets/` directly to GitHub. For bigger data workflows, I usually recommend the AWS-backed storage formats. You can enable data versioning in an S3 bucket through the AWS web console (though I have not tried personally).

**Comment by liutiming** [comment]
Thanks! Are you thinking more along the lines of git branch? That is really a cool idea! Though I am a bit weary that if I change my intermediate data a few times, won't the .git/object becomes unnecessarily huge? 

Pushing big datasets to cloud services is a nice idea too Re data backup but I foresee a lot of admin issues related to security and cost 😅

**Comment by liutiming** [comment]
Perhaps it is also worth pointing out that by separating into sub-projects, some of targets own limitation can be overcome e.g. calculation Re branching. I can see your point that this can get really hairy - I am mainly playing the devil's advocate here to imagine why a user may be inclined to do that.

**Comment by liutiming** [comment]
OK I think in the ideal situation the cost of storage should be much lower than the time cost of figuring out what was done before and computation cost of redoing the analysis. I realise I am spending a lot of my time figuring out which way to process data is the best (parameter to use, criteria to clean the data etc.) and often these thought process and EDA results are not properly documented. Worse still, the intermediate files are often overwritten when one method is chosen. It will be really nice to think of a way to properly document this process but at the same time show what the final chosen workflow is like so the intermediate files do not confuse the whole story. Git branch may be a way to do that. Thank you! Your suggestion is really insightful.

**Comment by liutiming** [comment]
I would very much like to see how targets can integrate with a version control system or provide a helper for that - git is not that well designed for an end user. Many of my colleagues are not sure how to use it so a data-science interface will be awesome. taken from xkcd.com:
![image](https://user-images.githubusercontent.com/39947942/103487320-56e6dd80-4dfc-11eb-96dc-865944887d23.png)

**Comment by wlandau** [comment]
The overall move in the R community seems to be to try to overcome the usability issue with more education, e.g. https://happygitwithr.com/. These days, R enthusiasts proselytize Git as much as they do Shiny and R Markdown, which says a lot about democratization. And for small projects, I think Git solves all the major versioning problems we would want in a data versioning tool.

But as you rightly brought up, Git has weaknesses. It's a monolith: large data objects all in one mysterious `.git/` directory. Having large data files could make branch switching intractably slow, which could make it impractical for large data. And if something in `.git/` gets corrupted and it's too big to back up on GitHub/GitLab/Bitbucket, then all the history is suddenly lost.

**Comment by wlandau** [comment]
If we pursue versioning, it needs to be in a separate package outside `targets`. Data versioning is a huge undertaking, more than big enough for its own tool. Plus, there are multiple possible technologies to build on and different approaches to versioning (do you want to make it easier to take experimental branches/digressions, or do you just want to leave a transparent audit trail?) and I think we want the freedom to try out each idea on its own.

**Comment by wlandau** [comment]
To to work around the Git monolith for medium-to-big data workflows, I think it makes sense to treat different branches/experiments as independent file systems. So let's say I start out with a new project, not necessarily with `targets`, and the file structure looks like this:

```r
.
+-- analysis.Rproj
+-- functions.R
+-- _targets/
+-- _targets.R
```

Then, my colleague Vivek asks me to pursue a digression I am not prepared for. Neither of us expect her question to become the major long-term focus of the project, but it does require me to make deep changes to my underlying functions. Either I invalidate the main set of targets, which is difficult to recover from, or I duplicate a ton of code in the same project, which is messy and unmaintainable.

Just thinking out loud, here's a tentative idea for a hypothetical new tool: create new experiments based the original project or other experiments.

```r
library(experiments) # tentative name
exp_new("vivek")
#> √ current project: "analysis" # maybe taken from the .Rproj file name
#> √ experiment: "vivek"
```

The file system turns into this:

```r
.
+-- analysis.Rproj
+-- functions.R
+-- _targets/
+-- _targets.R
+-- _experiment.yaml
+-- _experiments/
|    +-- vivek/
|    |    +-- vivek.Rproj
|    |    +-- functions.R
|    |    +-- _targets/
|    |    +-- _targets.R
|    |    +-- _experiment.yaml
```

The `_experiment.yaml` files could have metadata like date created, a description, custom user-defined tags, and the name of the parent experiment. (Experiments can branch into further experiments.) After creating the experiment using the tool, I open `vivek.Rproj` and work on the code for a while. 

```r
.
+-- analysis.Rproj
+-- functions.R
+-- _targets/
+-- _targets.R
+-- _experiment.yaml
+-- _experiments/
|    +-- vivek/
|    |    +-- vivek.Rproj
|    |    +-- vivek_functions.R # new functions
|    |    +-- vivek_utils.R # new file 
|    |    +-- _targets/
|    |    +-- _targets.R # changes to the pipeline
|    |    +-- _experiment.yaml # Maybe I edit this by hand.
```

At the same time, Anna asks me an equally challenging set of questions, which prompts more experiments.

```r
.
+-- analysis.Rproj
+-- functions.R
+-- _targets/
+-- _targets.R
+-- _experiment.yaml
+-- _experiments/
|    +-- vivek/
|    +-- anna/
|    +-- digression_1/ # branched from anna/
|    +-- digression_2/ # branched from anna/
```

After a while, can look back at all the experiments I did, using the `_experiment.yaml` files to link the parent/child relationships among experiments. In practice, this graph should not only show the names of the experiments, but also the creation date and brief description.

```r
exp_graph()
```

<img width="361" alt="graph" src="https://user-images.githubusercontent.com/1580860/103495282-42104700-4e08-11eb-9e80-0e3caae96193.PNG">

After working on each of the experiments independently, running the respective pipelines, and perusing the results, I find I like Vivek's analysis more than the original. Since we can assume all the pipelines have diverged at this point, and we have no version control software monitoring everything together (i.e. the monolith), we cannot reliably merge Vivek's project into the parent version. Instead, we swap can them. Below, our original analysis becomes an archived experiment, and Vivek's version becomes the main project. 

```r
.
+-- vivek.Rproj
+-- vivek_functions.R
+-- vivek_utils.R
+-- _targets/
+-- _targets.R
+-- _experiment.yaml
+-- _experiments/
|    +-- analysis/ # archived original experiment
|    +-- anna/
|    +-- digression_1/ # branched from anna/
|    +-- digression_2/ # branched from anna/
```

Because of the `_experiment.yaml` files, the parent/child relationships are still preserved, and we get the same graph to tell the story of our data analysis workflow.

```r
exp_graph()
```

<img width="361" alt="graph" src="https://user-images.githubusercontent.com/1580860/103495282-42104700-4e08-11eb-9e80-0e3caae96193.PNG">

**Comment by wlandau** [comment]
# What I like about the above

1. **Simplicity**. This hypothetical approach is low tech and transparent. Folks can instantly know exactly how it works understand exactly what it's doing every step of the way. That makes it easy to adopt mid-project.
1. **Compatibility** with Make-like pipeline tools. A lot of packages have their own systems for versioning, storage, and reproducibility: `archvist`, `storr`, `R.cache`, trackr`, `metaflow`, `orderly`, etc. However, all these systems require you to completely commit to a different way of storing data, which makes them incompatible with `targets`. But this hypothetical `experiments` package should not invalidate the pipelines it copies, and it lets you keep working on those pipelines in place.
1. **Selectivity**. Airflow-like pipeline tools save every version of every run you launch, which can sometimes make it hard to dig around for the results you actually care about. In this system, you only create an experiment when you need one, and you are not left to wade through a giant list of unnecessary model runs.

# Concerns

1. It doesn't seem like this hypothetical package does all that much. It just copies and shuffles around files. Maybe users do not need a special package for this.
1. Is this really a good way to manage experiments? It is unsophisticated compared to the Airflow-like tools out there, and it might make workflows messier in the long run.

**Comment by liutiming** [comment]
I think this can be very useful. I will be happy to test out this approach manually first. Thank you for the suggestion! 

I agree that Git is not really built for data science - another reason is that we do not often simultaneously work on the same code as others, but I will read Jenny's book to find out more.

**Comment by liutiming** [comment]
I don't think the book quite has a data science flavour to it? More like basic git and RStudio integration I feel... 

[Data Version Control · DVC](https://dvc.org/ "Data Version Control · DVC") may be of interest

**Comment by wlandau** [comment]
Yeah, DVC seems relevant because it uses Git just for code and serious big data storage for the heavy stuff. One might actually be able to use DVC on top of `targets` and just ignore DVC's pipeline/ML features, e.g. `dvc run`. That might be what we're looking for here.
