### ISSUE TITLE
Facilitate integration with RStudio build pane

### ISSUE THREAD

**Issue by petrbouchal** [wlandau/targets#258]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [ ] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

I found the  setup presented in https://ulhpc-tutorials.readthedocs.io/en/latest/maths/R/PS10_targets.html#18 very useful (build script running `tar_make()` recognised in RStudio's build pane). I wonder if the package itself could facilitate this setup?

What I think this would mean => a possible way of implementing it

- make it easier to create a build script => provide a helper function analogous to tar_script() + make the script executable on UNIX machines (not sure if anything like that is required on Windows)
- integrate with RStudio build pane => either by providing a hint to the user in a message, or by updating the Rproj file (directly or perhaps {rstudioapi} can help)
- provide an indication at the end of `tar_make()`'s output that the pipeline has finished running (similar to package build/test/document commands). There is a summary-type line when all targets are skipped ("Already up to date") but not when some run; for both cases a message that stands out more might be useful.

The last bit would be worthwhile and I expect low-cost regardless of what you think of the previous two - happy to submit as a separate issue if you wish.

**Comment by wlandau** [comment]
> I found the setup presented in https://ulhpc-tutorials.readthedocs.io/en/latest/maths/R/PS10_targets.html#18 very useful 

That's an excellent resource, thanks for sharing.

> (build script running tar_make() recognised in RStudio's build pane). I wonder if the package itself could facilitate this setup?... make it easier to create a build script => provide a helper function analogous to tar_script() + make the script executable on UNIX machines (not sure if anything like that is required on Windows)

I will keep it in mind, but given how easy it is to create one-line scripts with `targets::tar_make()`, my current preference is to leave users to create their own. There is always a cost to new API functions.

> integrate with RStudio build pane => either by providing a hint to the user in a message, 

I like to keep messages to a minimum so the stdout looks clean. I feel traditional documentation is more effective than hint messages.

> or by updating the Rproj file (directly or perhaps {rstudioapi} can help)

Most of `targets` is intentionally IDE agnostic, with the exception of RStudio addins. I believe this policy sets clear boundaries for integration with RStudio.

Can the build pane be invoked from an addin? Because I could picture an addin that writes a `targets::tar_make()` script to a `tempfile()` and then launches it in the build pane all in one click. If you think that is possible, feel free to open a new issue / PR.

> provide an indication at the end of tar_make()'s output that the pipeline has finished running (similar to package build/test/document commands). There is a summary-type line when all targets are skipped ("Already up to date") but not when some run; for both cases a message that stands out more might be useful.

I like that. Added in 9b901de200b48b1c0265b6722cdeaf59e4927bbb.

**Comment by petrbouchal** [comment]
Many thanks - appreciate the fix you pointed to. I get the reasoning behind your other responses.

> my current preference is to leave users to create their own

My thinking was mostly around alleviating the hassle of creating the script which will look the same in all projects and requires the same steps (create file, insert shebang, insert R line, make executable, insert path into Rproj/project options) but I agree that users of {targets} are typically skilled enough to automating this themselves.

> Can the build pane be invoked from an addin? I could picture an addin that writes a targets::tar_make() script to a tempfile() and then launches it in the build pane all in one click.

I can't see anything to that effect in {rstudioapi} at a quick glance. I also think the benefit would have been mostly in tapping the muscle memory of clicking the Build button / pressing ctrl+shift+B that people have from package development and other workflows. As a shortcut for just running the pipeline, I think the existing addins are enough; having the output appear in the Build pane won't be worth the trouble of figuring this out.

**Comment by wlandau** [comment]
> My thinking was mostly around alleviating the hassle of creating the script which will look the same in all projects and requires the same steps (create file, insert shebang, insert R line, make executable, insert path into Rproj/project options) but I agree that users of {targets} are typically skilled enough to automating this themselves.

For a tool like `targets`, I worry about overfitting to user-specific paths like `/usr/bin/env` and assuming everyone will want `tar_make()` rather than `tar_make_clustermq()`. Though it might be a good fit for a tool like [`dflow`](https://github.com/MilesMcBain/dflow) (built for `drake`, not `targets`, but Miles did express interest in supporting `targets` in a similar way through a separate package).

**Comment by petrbouchal** [comment]
That makes good sense - thanks for the reminder about dflow.

**Comment by sctyner** [comment]
Just popping in to say that we use `targets` on my team, and my colleague Todd has written a package [tarflow](https://github.com/toddgrabowsky/tarflow), modeled after Miles' dflow package.

**Comment by petrbouchal** [comment]
Excellent, thank you! Will do.

**Comment by wlandau** [comment]
That sounds awesome, Sam! Thanks for sharing. FYI @MilesMcBain.
