### ISSUE TITLE
max_expand

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau/targets#56]

**Comment by kendonB** [comment]
@wlandau are you willing to reconsider this one? I think that altering commands for test mode is quite error-prone and is only just as easy when there is a single item being mapped over. Multiple items in `cross` and `map`s present more opportunity for errors when compared to the old max_expand.

**Comment by wlandau** [comment]
One of the biggest mistakes I made with `drake` was building too many nonessential features deep in the codebase. This time around, I intend to keep the core components as small, simple, and tech-debt-free as possible. [`tarchetypes`](https://github.com/wlandau/tarchetypes) is a safer place for features like `max_expand` which only occasionally get used. Here's one way we might handle this at the `tarchetypes` level. Example pipeline:

```r
# _targets.R
library(targets)
tar_pipeline(
  tar_target(x, seq_len(100)),
  tar_target(y, seq_len(100)),
  tar_target(z, x + y, pattern = map(x, y))
)
```

A downsized version of the pipeline for testing purposes could look like this:

```r
# _targets.R
library(targets)
tar_pipeline(
  tar_target(x, seq_len(100))),
  tar_target(y, seq_len(100))),
  tar_target(x_slice, vctrs::vec_slice(x, seq_len(2))),
  tar_target(y_slice, vctrs::vec_slice(y, seq_len(2))),
  tar_target(z, x + y, pattern = map(x_slice, y_slice))
)
```

A new `tar_slice()` function in `tarchetypes` might express the above like this:

```r
# _targets.R
library(targets)
tar_pipeline(
  tar_target(x, seq_len(100)),
  tar_target(y, seq_len(100)),
  tar_slice(tar_target(z, x + y, pattern = map(x, y)), seq_len(2))
)
```

That particular version might not be ideal because switching back to production mode would invalidate the test branches of `z`, but I think it's in the general ballpark we should explore.

**Comment by wlandau** [comment]
I think #212 is the way to handle this. For example, we could implement new `head()` method to take the first few branches. `pattern = map(head(x), head(y))` could be a `max_expand`-like alternative to `pattern = map(x, y)`.

**Comment by wlandau** [comment]
New `sample()` and `tail()` methods could behave similarly.

**Comment by mattwarkentin** [comment]
`sample()` is interesting, such as for random grid search, but there would have to be a good way to report which values were sampled. I wonder if things like this are best left for the user to do manually in a separate target? Same would be true for `head()` and `tail()`, possibly.

**Comment by wlandau** [comment]
> sample() is interesting, such as for random grid search, but there would have to be a good way to report which values were sampled.

Individual branch names are possible to get with some digging, but I do not think they are usually informative. Workflows are usually better off when the individual branches contain informative metadata (for example, in columns of a small `tibble`).

> I wonder if things like this are best left for the user to do manually in a separate target?

The trouble is that separate targets duplicate data. And for the purposes of `max_expand`, we want something as seamless as possible for the user.

**Comment by wlandau** [comment]
Note to self: evaluate patterns with the seed of the target so `sample()` is reproducible.

**Comment by mattwarkentin** [comment]
`targets` got a shout-out during the `torch` deep learning talk...FYI

![Screen Shot 2020-11-13 at 4 02 53 PM](https://user-images.githubusercontent.com/27825069/99121028-e248ad00-25c9-11eb-8007-ea1292dc8b7c.png)

**Comment by wlandau** [comment]
Wow, that's so cool!
